server {
    listen 80;

    # 파일 업로드 용량 제한을 20MB로 상향 (기본값은 1MB)
    client_max_body_size 20M;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

     # 백엔드 API (프론트 /admin 페이지와 겹치지 않게 admin 제거)
      location ~ ^/(api|users|oauth2|login/oauth2|uploads) {
          proxy_pass http://52.78.88.19:8090;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
      }

      # 백엔드 어드민 API: /admin-api/* → 백엔드 /admin/*
      location /admin-api/ {
          rewrite ^/admin-api/(.*)$ /admin/$1 break;
          proxy_pass http://52.78.88.19:8090;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
      }
}